# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_loop_system/protocol/pb_env.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'agent_loop_system/protocol/pb_env.proto\x12\x1a\x61gent_loop_system.protocol\"\xd9\x01\n\x0c_AuthRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x10\n\x08\x61uthCode\x18\x06 \x01(\t\x12\x33\n\x04user\x18\x07 \x01(\x0b\x32%.agent_loop_system.protocol._UserInfo\x12\x33\n\x04time\x18\x08 \x01(\x0b\x32%.agent_loop_system.protocol._TimeInfo\"C\n\r_AuthResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65verBind\x18\x02 \x01(\x05\x12\x10\n\x08\x62indTime\x18\x03 \x01(\x03\"H\n\t_UserInfo\x12\x0e\n\x06gender\x18\x01 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0e\n\x06weight\x18\x04 \x01(\x02\"2\n\t_TimeInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x12\n\nzoneOffset\x18\x02 \x01(\x11\"!\n\x0f_UnAuthResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"/\n\x0c_BatteryInfo\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x10\n\x08\x63harging\x18\x02 \x01(\x05\"!\n\r_LanguageInfo\x12\x10\n\x08language\x18\x01 \x01(\x05\"o\n\n_AppStatus\x12\x14\n\x0cisForeground\x18\x01 \x01(\x05\x12\x15\n\rpermissionSms\x18\x02 \x01(\x05\x12\x1a\n\x12permissionLocation\x18\x03 \x01(\x05\x12\x18\n\x10permissionCamera\x18\x04 \x01(\x05\"\x1e\n\r_LanguageList\x12\r\n\x05items\x18\x01 \x01(\x0c\"A\n\r_LocationInfo\x12\x11\n\tlongitude\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x0b\n\x03snr\x18\x03 \x01(\x05\"{\n\x0e_BluetoothInfo\x12\x0f\n\x07\x62le_mac\x18\x01 \x01(\t\x12\x10\n\x08\x62le_name\x18\x02 \x01(\t\x12\x12\n\nble_status\x18\x03 \x01(\x05\x12\x0e\n\x06\x62t_mac\x18\x04 \x01(\t\x12\x0f\n\x07\x62t_name\x18\x05 \x01(\t\x12\x11\n\tbt_status\x18\x06 \x01(\x05\x42+\n\'com.topstep.wearkit.prototb.internal.pbP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_loop_system.protocol.pb_env_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.topstep.wearkit.prototb.internal.pbP\001'
  _globals['__AUTHREQUEST']._serialized_start=72
  _globals['__AUTHREQUEST']._serialized_end=289
  _globals['__AUTHRESPONSE']._serialized_start=291
  _globals['__AUTHRESPONSE']._serialized_end=358
  _globals['__USERINFO']._serialized_start=360
  _globals['__USERINFO']._serialized_end=432
  _globals['__TIMEINFO']._serialized_start=434
  _globals['__TIMEINFO']._serialized_end=484
  _globals['__UNAUTHRESPONSE']._serialized_start=486
  _globals['__UNAUTHRESPONSE']._serialized_end=519
  _globals['__BATTERYINFO']._serialized_start=521
  _globals['__BATTERYINFO']._serialized_end=568
  _globals['__LANGUAGEINFO']._serialized_start=570
  _globals['__LANGUAGEINFO']._serialized_end=603
  _globals['__APPSTATUS']._serialized_start=605
  _globals['__APPSTATUS']._serialized_end=716
  _globals['__LANGUAGELIST']._serialized_start=718
  _globals['__LANGUAGELIST']._serialized_end=748
  _globals['__LOCATIONINFO']._serialized_start=750
  _globals['__LOCATIONINFO']._serialized_end=815
  _globals['__BLUETOOTHINFO']._serialized_start=817
  _globals['__BLUETOOTHINFO']._serialized_end=940
# @@protoc_insertion_point(module_scope)
