# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_loop_system/protocol/pb_notice.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*agent_loop_system/protocol/pb_notice.proto\x12\x1a\x61gent_loop_system.protocol\":\n\n_AppNotice\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"=\n\x10_TelephonyNotice\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"A\n\x0e_HangupRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0f\n\x07\x65ndCall\x18\x02 \x01(\x05\x12\x0f\n\x07sendSms\x18\x03 \x01(\t\"3\n\x0f_HangupResponse\x12\x0f\n\x07\x65ndCall\x18\x01 \x01(\x05\x12\x0f\n\x07sendSms\x18\x02 \x01(\x05\"\x1c\n\x0b_SOSRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"\x18\n\t_QuickCmd\x12\x0b\n\x03\x63md\x18\x01 \x01(\tB+\n\'com.topstep.wearkit.prototb.internal.pbP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_loop_system.protocol.pb_notice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'com.topstep.wearkit.prototb.internal.pbP\001'
  _globals['__APPNOTICE']._serialized_start=74
  _globals['__APPNOTICE']._serialized_end=132
  _globals['__TELEPHONYNOTICE']._serialized_start=134
  _globals['__TELEPHONYNOTICE']._serialized_end=195
  _globals['__HANGUPREQUEST']._serialized_start=197
  _globals['__HANGUPREQUEST']._serialized_end=262
  _globals['__HANGUPRESPONSE']._serialized_start=264
  _globals['__HANGUPRESPONSE']._serialized_end=315
  _globals['__SOSREQUEST']._serialized_start=317
  _globals['__SOSREQUEST']._serialized_end=345
  _globals['__QUICKCMD']._serialized_start=347
  _globals['__QUICKCMD']._serialized_end=371
# @@protoc_insertion_point(module_scope)
